### PR TITLE
Allow alephant preview to support batch get request

### PR DESCRIPTION
**Pull request by samfrench**
Allow alephant preview to support batch get request

_Also run Rubocop on all files in this repo_

https://jira.dev.bbc.co.uk/browse/CONNPOL-3475

### CODE REVIEW

**Comment by samfrench** [comment]
@dazoakley, can you review this one please?

Note, the first commit is the intended change. The second commit was Rubocop. I could have done this in multiple PRs, but decided to bundle together.

**Comment by dazoakley** [comment]
@samfrench first commit looks ok to me, but the tests are failing on CI.

**Comment by samfrench** [comment]
I noticed that. It appears that newer versions of guard, use the listen gem. This isn't supported by the version of ruby we use. I've pushed a fix now. https://github.com/BBC-News/alephant-preview/pull/16/commits/df541c0580b38ee09de2b95c8b45bcd087048ce6

**Comment by dazoakley** [comment]
👍

**Pull request merged**
